version: '3.7'

services:
  web:
    build: ./server/
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backups:/fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build: ./database
    environment:
      POSTGRES_USER: ynchacks
      POSTGRES_PASSWORD: password
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/postgresql/
    command: -p 5433

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=ynchacks@yalenus.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports:
  #     - "6000"
  #   depends_on:
  #     - db

volumes:
  postgres_data: